# Generated by Django 3.2.3 on 2024-08-28 18:01

from django.db import migrations, models
import urlshortener.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkShortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_hash', models.CharField(default=urlshortener.models.get_hash, max_length=12, unique=True)),
                ('url_original', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
