# Generated by Django 3.2.3 on 2024-08-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingridient',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='IngridientRecipe',
            new_name='IngredientRecipe',
        ),
    ]
