# Generated by Django 3.2.3 on 2024-08-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_ingredient_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='unit_of_measurement',
            new_name='measurement_unit',
        ),
    ]
