# Generated by Django 3.2.3 on 2024-08-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20240817_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='ingridient',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingridients',
            new_name='ingredient',
        ),
    ]
