# Generated by Django 3.2.3 on 2024-08-18 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20240818_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
