# Generated by Django 3.2.3 on 2024-08-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_rename_ingredients_ingredientrecipe_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
