# Generated by Django 3.2.3 on 2024-08-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_rename_ingredients_recipe_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
