# Generated by Django 3.2.3 on 2024-08-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20240818_1756'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
