# Generated by Django 3.2.3 on 2024-08-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240820_2320'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subsribe',
            name='unique_follow',
        ),
    ]
